### ISSUE TITLE
[StackSpot Labs] Apoio criação de conteúdo parceiros (SunnySystems)

### ISSUE THREAD

**Issue by eduardocolombo** [zup-archive/stackspot-studio-data-roadmap#107]
### Descrição
Realizar contato com possíveis parceiros para criação de conteúdo dentro da StackSpot e apoiar os parceiros na criação de Stacks/Plugins.

### DOD
Conteúdo validado e publicado no StackSpot EDP

### Tasks
- [x] Marcar Reunião com time Sunny Systems (e/outros) para entender o contexto
- [x] Dispobilizar acesso a StackSpot na org Labs (Usuários e Times)
- [x] Criar Studio, Workspace e publicar Stacks de App (Java, Node, Python)
- [ ] Realizar curadoria do(s) conteúdo(s) gerados pelos parceiros

**Comment by danielmaion** [comment]
Alguns pontos levantado da primeira conversa com Sunny Systems:

- Para o Reinvent:
Quais conteúdos serão colocados (são revendedores, podemos colocar o que eles revendem lá dentro? Ou só produtos próprios?)
Ideal seria ter um case de algum cliente da StackSpot utilizando os produtos da Sunny. (Imagem com fluxo que eles desenharam sem muito conhecimento da stackspot)
Precisamos entender a dinâmica da presença do stackspot no reinventar
Lucas, COO (?) da Sunny, gostaria de estar presente no Reinvent, caso a gente leve o case deles.
Hub: Como estarão apresentados dentro da stackspot? Aparecerá Sunny ou “studio de observabilidade”?

- Próximos passos:
Papo técnico para apresentar como conteúdos serão criados

- Parceria comercial
É possível Sunny Vender stackspot? Quem precisamos envolver para bater esse martelo e defini modelo comercial?

- Outras dúvidas
Sunny vende Datadog, o que faremos se outros parceiros quiserem vender datados? E se o próprio DataDog quiser entrar na Stackspot?
Como a stackspot lida com revendedores?
