### ISSUE TITLE
[StackSpot AI] Criação de KS e Snippets para Infra

### ISSUE THREAD

**Issue by danielmaion** [zup-archive/stackspot-studio-data-roadmap#109]
### Descrição
Criação de novos Knowledge Sources e Code Snippets para o StackSpot AI contemplando aspectos de infraestrutura que o atual Code Buddy não atende as necessidades.

### Tasks
- [x] Geração de buildspec.yaml da aplicação para deploy em esteira (GPT/CodeBuddy já gera automático de forma satisfatória)
- [x] Geração de arquivo json de task definition deploy ECS (GPT/CodeBuddy já gera automático de forma satisfatória)
- [x] Geração de workflow para deploy no GitHub Actions
- [x] Dockerfile de ferramentas e aplicações Padrões

### DOD
Code Snippets criados e validados via StackSpot AI

**Comment by danielmaion** [comment]
- Criado um KS para stackspot-runtime-engine contendo informações de GitHub Actions e Workflows para deploy de infra compartilhada utilizando Runtime Engine v2. https://ai.stackspot.com/code-buddy/knowledge-sources/stackspot-runtime-engine

- KS para Dockerfile e futuros arquivos Docker: https://ai.stackspot.com/code-buddy/knowledge-sources/docker-application
Foi adicionado principais Dockerfile de Stacks de App e futuramente poderá ser acrescentado dado a entrada de novos projetos no StackSpot Labs que não está coberto pela IA.
