### ISSUE TITLE
[StackSpot Labs] DesignDoc para SecGov - Proposta nova org GitHub

### ISSUE THREAD

**Issue by danielmaion** [zup-archive/stackspot-studio-data-roadmap#110]
### Descrição
Esta atividade tem como objetivo a elaboração do DesignDoc e validação com time de SecGov para criação de uma nova organização no GitHub que servirá para publicação de plugins, stacks e conteúdos na StackSpot Community Hub/StackSpot Labs.

### DoD
Criação e validação do DesignDoc com time de SecGov. 

Pontos de contato:
- bruno.duru@zup.com.br
- mario.figueiredo@zup.com.br

### Tasks
- [x] Criar DesignDoc com diretrizes InnerSource
- [x] Validar doc com SecGov
- [x] Acompanhar criação nova Org

**Comment by danielmaion** [comment]
Documento DesignDoc para nova org:
https://docs.google.com/document/d/1bcR3fLKxm8UXtSXL9_qnFTc5sK43xVBQm0bQ-su6kz8/edit#heading=h.r33esi2ah3w9

**Comment by danielmaion** [comment]
Aguardado validação com SecGov para prosseguir com criação de nova Organização e migração de repositórios de conteúdos.
