### ISSUE TITLE
[StackSpot AI] Criação de agentes usando o Code Buddy para apresentação no OT.

### ISSUE THREAD

**Issue by adiropv** [zup-archive/stackspot-studio-data-roadmap#113]
### Descrição

Criação de agentes (Software 3.0) utilizando o code buddy para demonstrar a capacidade de assistência do produto.

- Agente para análise de Sentimento.
- Chat enviando pix de contatos salvos(COM A API DE MOCK DO PIX).

### Tasks

- [x] Estruturar projeto.
- [x] Criação do agente para analise de sentimento.
- [x] Criação de API mock do PIX com OpenAPI.
- [x] Criação de agente para integração do PIX.

### DOD
Demonstração dos agentes para o OT e agentes finalizados prontos para teste.
