### ISSUE TITLE
[StackSpot Labs] Criação de Stack AI para Apps

### ISSUE THREAD

**Issue by elpasckezup** [zup-archive/stackspot-studio-data-roadmap#120]
### Descrição
Criar Studio e Stacks AI para dar suporte a geração de código.

### DOD
Conteúdo validado e publicado no StackSpot AI

### Tasks (Criar Stacks AI):
- [x] Java + Spring
- [x] Java + Micronaut
- [x] Java + Quarkus
- [x] Kotlin + Spring
- [x] Kotlin + Micronaut
- [x] Node.JS + Express+ TypeScript
- [ ] Angular
- [ ] React + Next
- [ ] Vue.js + Nuxt
- [x] Python + FastAPI + Pytest
- [ ] .NET
