### ISSUE TITLE
[StackSpot Labs] Criação de Action para publicação em lote de KS APIs

### ISSUE THREAD

**Issue by adiropv** [zup-archive/stackspot-studio-data-roadmap#134]
### Descrição
Action para coletar contratos de API no API Gateway e publicar em lote no Stack AI como KS do tipo API.

### DOD
Conteúdo validado e publicado no StackSpot AI

### Tasks (Criar Stacks AI):

- [x] Criação do projeto da action
- [x] Coleta dos dados do API Gateway
- [x] Cadastro em lote das APIs

**Comment by adiropv** [comment]
Primeira versão da action finalizada e publicada com as funcionalidades básicas

Repositório (Org Labs)
https://github.com/StackSpot-Labs/stk-action-openapi-knowledge-source-api

EDP
https://app.stackspot.com/en/stackspot-labs/studios/data-labs/actions/action-openapi-knowledge-source-api
