### ISSUE TITLE
[StackSpot AI] Criação de APIs Dados Financeiros

### ISSUE THREAD

**Issue by fernandosantoszup** [zup-archive/stackspot-studio-data-roadmap#135]
**Tasks**

Dados Financeiros
- [x] API Open Finance / API Open Banking
- [ ] API Febraban (não encontrado API Publica)
- [ ] API Anatel (não encontrado API Publica)
- [x] API do Banco Itaú

**Comment by luizcarloszup** [comment]
Link Open Finance/Open Banking
https://openbanking-brasil.github.io/openapi/swagger-apis/common/1.0.2.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/admin/1.0.2.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/channels/1.0.2.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/products-services/1.0.2.yml,
https://raw.githubusercontent.com/OpenBanking-Brasil/openapi/main/swagger-apis/consents/2.2.0.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/resources/2.1.0.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/customers/2.0.1.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/credit-cards/2.1.0.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/accounts/2.1.0.yml,
https://raw.githubusercontent.com/OpenBanking-Brasil/openapi/main/swagger-apis/loans/2.1.0.yml,
https://raw.githubusercontent.com/OpenBanking-Brasil/openapi/main/swagger-apis/financings/2.1.0.yml,
https://raw.githubusercontent.com/OpenBanking-Brasil/openapi/main/swagger-apis/unarranged-accounts-overdraft/2.1.0.yml,
https://raw.githubusercontent.com/OpenBanking-Brasil/openapi/main/swagger-apis/invoice-financings/2.1.0.yml,
https://raw.githubusercontent.com/OpenBanking-Brasil/openapi/main/swagger-apis/payments/3.0.0.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/enrollments/1.1.0.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/capitalization-bonds/1.0.1.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/investments/1.0.0.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/exchange/1.0.0.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/acquiring-services/1.0.0.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/pension/1.0.1.yml,
https://openbanking-brasil.github.io/openapi/swagger-apis/insurances/1.0.1.yml
