### ISSUE TITLE
[StackSpot Labs] Criação de Action para publicação em lote de issues do Github em KS Snippets

### ISSUE THREAD

**Issue by adiropv** [zup-archive/stackspot-studio-data-roadmap#147]
### Descrição
Action para coletar issues de um repositório do Github e alimentar um KS do tipo Snippets.

### DOD
Conteúdo validado e publicado no StackSpot AI

### Tasks (Criar Stacks AI):

- [x] Criação do projeto da action
- [x] Coleta das issues de um repo do Github
- [x] Cadastro em lote das issues
