### ISSUE TITLE
[StackSpot Labs] Criação de Action para publicação em lote de dados do Jira em KS Snippets

### ISSUE THREAD

**Issue by adiropv** [zup-archive/stackspot-studio-data-roadmap#149]
### Descrição

Action para coletar dados do Jira e alimentar um KS do tipo Snippets.

### DOD
Conteúdo validado e publicado no StackSpot AI

### Tasks (Criar Stacks AI):

- [ ] Criação do projeto da action
- [ ] Coleta dos dados de uma instância do Jira
- [ ] Cadastro em lote dos dados
