### ISSUE TITLE
Research - Benchmark sobre IDPs concorrentes do Stackspot

### ISSUE THREAD

**Issue by flavioaraujozup** [zup-archive/stackspot-studio-data-roadmap#20]
### **Descrição**

Benchmark comparando Stackspot com 5 vendors de IDPs promissores de acordo com a Gartner: Backstage, Humanitec, Cortex e Garden.

### **DOD**

Apresentação com tabela comparativa entre as 6 plataformas, apontando quais os requisitos básicos de um IDP e quais os possíveis diferenciais

**Tasks**

- [x] Tabela comparativa entre Stackspot e os 5 vendors da Gartner
- [x] Validação com time técnico da Stackspot
- [x] Construção da apresentação final
- [x] Inclusão de precificação e modelo de negócio

**Comment by fernandosantoszup** [comment]
https://docs.google.com/spreadsheets/d/1yh3-vPPSqRVcB5Y3FoVglZ5teoTkTEX7tyzWUWYGq6I/edit#gid=403600131 Documento com a tabela do benchmark

**Comment by fernandosantoszup** [comment]
Apresentação

https://docs.google.com/presentation/d/1HdrYDx1XoEkrGiyD8Rfr2v4sgJ-lgKNgrPIkb2i7f5g/edit#slide=id.g1e5200d5e1f_0_36
