### ISSUE TITLE
Stack Java + Spring

### ISSUE THREAD

**Issue by flavioaraujozup** [zup-archive/stackspot-studio-data-roadmap#30]
### Objetivo

Desenvolver uma stack que seja referência de mercado adotando as melhores práticas.

Material de pesquisa: 

https://docs.google.com/presentation/d/1r6vwIiHI-l7B1wj-7vPgg2ehLZEN7afKOV4jO5h93Rs/edit#slide=id.g1e518cf6467_0_62

### DoD:

- Ter a Stack Publicada no Portal da Stack Spot
- Ter a documentação da Stack explicando como está composta

### Subs Tasks

- [ ] https://github.com/stack-spot/supporting-content-app-java-spring-base/issues/2
- [x] https://github.com/stack-spot/stackspot-studio-content-roadmap/issues/61

### Tasks
- supporting-content-app-java-spring-api
- supporting-content-app-java-spring-jpa
- supporting-content-app-java-git-pipeline

**Criar plugins de infraestrutura**

- [x] supporting-content-cloud-base
- [x] supporting-content-cloud-aws-rds
- [x] supporting-content-cloud-aws-eks-app
- [x] supporting-content-cloud-aws-github-iam
- [x] supporting-content-cloud-aws-eks-cluster
- [x] supporting-content-cloud-aws-eks-ingress-nginx

**Diversos**

- [ ] solicitar repositório e configurá-lo para reuso de workflows para evitar duplicação e facilitar a manutenção
- [ ] solicitar repositório e configurá-lo para testes de implatação de apps e infra
