### ISSUE TITLE
Research - Mapeamento de Stacks e Tecnologias utilizadas em ambiente Zup, Itaú e Mercado

### ISSUE THREAD

**Issue by fernandosantoszup** [zup-archive/stackspot-studio-data-roadmap#45]
### Descrição

Fazer um levantamento das principais tecnologias e stacks utilizadas na:

- Z-Unit (identificando os clientes)
- Builders Hub (Itaú)
- StackSpot (divindo Core e Conteúdo)
- Mercado (incluindo tendências para o futuro)

### DoD
Apresentação indicando quais as tecnologias deveriam ser prioridade de construção para área de conteúdo

### Tasks

- [x] Coletar dados dos clientes Z-Unit
- [x] Coletar dados do Itaú
- [x] Coletar dados de StackSpot conteúdo
- [x] Coletar dados de StackSpot core components
- [x] Coletar dados do mercado atual
- [x] Coletar dados de tendências
- [x] Listar os aprendizados
- [x] Construir apresentação
- [x] Construir matriz consolidando resultados
