### ISSUE TITLE
Research - Bench de MLops

### ISSUE THREAD

**Issue by flavioaraujozup** [zup-archive/stackspot-studio-data-roadmap#52]
### **Descrição**

Benchmark comparando as seguintes ferramentas de MLOps:

MLflow
Kubeflow
Metaflow
Sage Maker
Google Cloud AI Platform - Vertex AI concorrente Sagemaker
Azure Machine learning
DVC
Seldon
Domino Data Lab
DataRobot
H2O.ai
Weights & Biases
prefect.io
kedro.org
Katonic.ai

### **DOD**

Apresentação com tabela comparativa entre as plataformas, apontando quais os requisitos básicos de um produto de MLOps (Licença para operar) e quais os possíveis diferenciais (licença para competir e vencer)

**Tasks**

- [x] Listar features de comparação
- [x] Validar lista com time técnico
- [x] Definir players
- [x] Construir o benchmark
- [x] Validar tabela com time técnico
- [x] Construir apresentação

**Comment by fernandosantoszup** [comment]
Tabela de benchmark https://docs.google.com/spreadsheets/d/1imHzP5uD-5c4ubuwCiyPhISsASCGV8nrmsJttk2q4nY/edit#gid=1123411942

PPT: https://docs.google.com/presentation/d/1gGMeSymjBt59sZUl62xJBEWMzyDfnRmFw8ZNRFCQw90/edit#slide=id.g1e6030d72e1_0_6
