### ISSUE TITLE
Research - Bench + Mercado de Data Quality + Observability

### ISSUE THREAD

**Issue by flavioaraujozup** [zup-archive/stackspot-studio-data-roadmap#53]
### **Descrição**

Pesquisa de mercado e benchmark de soluções de Data Quality e Observabilidade, para entendermos a o potencial financeiro neste segmento e quais os principais players presentes.

### **DOD**

Apresentar o tamanho do mercado atual de observabilidade e qualidade de dados em dólares e a projeção de crescimento para os próximos anos. Também é necessário construir uma tabela comparativa entre as plataformas, apontando quais os requisitos básicos de um produto de Qualidade e pra um de Observabilidade (Licença para operar) e quais os possíveis diferenciais (licença para competir e vencer)

**Tasks**

- [x] Preencher tabela com features já definidas pelo time técnico
- [x] Mensurar o tamanho do mercado atual de qualidade
- [x] Mensurar o tamanho do mercado atual de observabilidade
- [x] Mensurar o tamanho do mercado futuro de qualidade
- [x] Mensurar o tamanho do mercado futuro de observabilidade
- [x] Consolidar resultados em uma apresentação

**Comment by fernandosantoszup** [comment]
Link do PPT:

https://docs.google.com/presentation/d/1YS2ZU39-Drg-6zB9wXRdF6qIlpaEPG7H_rewHYwr9c0/edit#slide=id.g1b7f692dc55_1_0
